### ISSUE TITLE
Add support for authentication

### ISSUE THREAD

**Issue by thg1101** [twolfson/grunt-curl#34] opened 2015-09-07 14:14 UTC
Adding support for the -u CLI parameter, especially with :x-oauth-basic would enable (among, I'm sure, other things) downloading from private GIT repos, and negate the need for bower for simple dependencies

**Comment by twolfson** [comment] 2015-09-11 03:28
Sorry for the slow reply. This issue is a duplicate of #32. Here is a copy/paste of the example, please see the issue for more information:

```js
src: {
  url: 'http://google.com',
  auth: {
    username: 'foo',
    password: 'bar'
  }
}
```

**Closed by twolfson** 2015-09-11 03:28 UTC
